"""outline — 故事大纲（campaign / volume）与卷边界提议。
"""

from trpg2novel.outline.context import build_outline_context
from trpg2novel.outline.generate import generate_campaign_outline, generate_volume_outline
from trpg2novel.outline.io import (
    campaign_outline_yaml,
    ensure_outline_dirs,
    list_volumes,
    load_campaign_outline,
    load_volume_outline,
    promote_draft_to_final,
    save_campaign_outline,
    save_volume_outline,
    volume_history_dir,
    volume_yaml_path,
    outline_dir,
    volumes_dir,
)
from trpg2novel.outline.lifecycle import (
    clear_pending_pool,
    classify_scenes,
    find_volume,
    mark_closed,
    mark_drafting,
    next_volume_index,
    promote_to_confirmed,
    register_volume_draft,
    remaining_scene_ids_for_next_volume,
    remove_uncommitted_volume,
    set_pending_pool,
)
from trpg2novel.outline.propose import VolumeProposal, VolumeProposalResult, proposal_to_outline, propose_volumes
from trpg2novel.outline.revise import (
    CampaignRevisionProposal,
    apply_revision,
    propose_campaign_revision,
)
from trpg2novel.outline.roster import (
    RosterChange,
    apply_key_character_changes,
    compute_volume_roster,
    sync_key_characters_from_cards,
)
from trpg2novel.outline.schema import (
    CampaignOutline,
    EmotionBeat,
    EvolutionNote,
    JoiningCharacter,
    KeyBeat,
    KeyCharacter,
    MajorArc,
    RetiringCharacter,
    Subplot,
    VolumeOutline,
    VolumePlanItem,
    VolumeRoster,
)
from trpg2novel.outline.scene_summary import (
    SceneSummary,
    SceneSummaryCache,
    batch_generate_summaries,
    cache_path,
    generate_scene_summary,
    get_or_generate_scene_summary,
    list_missing_summaries,
    load_summary_cache,
    save_summary_cache,
)
from trpg2novel.state.story_state import PendingScenePool, VolumeRecord

__all__ = [
    "apply_revision",
    "CampaignRevisionProposal",
    "SceneSummary",
    "SceneSummaryCache",
    "VolumeProposal",
    "VolumeProposalResult",
    "propose_campaign_revision",
    "batch_generate_summaries",
    "build_outline_context",
    "cache_path",
    "campaign_outline_yaml",
    "clear_pending_pool",
    "classify_scenes",
    "compute_volume_roster",
    "EmotionBeat",
    "EvolutionNote",
    "find_volume",
    "generate_campaign_outline",
    "generate_scene_summary",
    "generate_volume_outline",
    "get_or_generate_scene_summary",
    "JoiningCharacter",
    "KeyBeat",
    "KeyCharacter",
    "list_missing_summaries",
    "load_campaign_outline",
    "load_summary_cache",
    "load_volume_outline",
    "mark_closed",
    "mark_drafting",
    "MajorArc",
    "next_volume_index",
    "outline_dir",
    "PendingScenePool",
    "promote_draft_to_final",
    "promote_to_confirmed",
    "proposal_to_outline",
    "propose_volumes",
    "register_volume_draft",
    "remaining_scene_ids_for_next_volume",
    "remove_uncommitted_volume",
    "RetiringCharacter",
    "RosterChange",
    "save_campaign_outline",
    "save_summary_cache",
    "save_volume_outline",
    "set_pending_pool",
    "Subplot",
    "sync_key_characters_from_cards",
    "VolumeOutline",
    "VolumePlanItem",
    "VolumeRecord",
    "VolumeRoster",
    "volumes_dir",
    "volume_history_dir",
    "volume_yaml_path",
]
